### ISSUE TITLE
Kernel version missing

### ISSUE THREAD

**Issue by dcabrejas** [ktdreyer/facetimehd-kmod-rpm#1]
Hi,

I have just come across this, I was pleasantly surprised. 
However I can't find the rpm for my kernel : `4.16.3-301.fc28.x86_64` at https://ktdreyer.fedorapeople.org/macbook/

I also don't know how to add this repo to dnf so that I can use the `dnf install` command shown on the README file. 

Is there no way to install this for my kernel?

Thank you.

**Comment by ktdreyer** [comment]
Thanks Diego!

Unfortunately that Fedora 28 kernel is quite old. Are you able to update to the latest one?

**Comment by ktdreyer** [comment]
I've updated the README today to make using this a little easier.

**Comment by dcabrejas** [comment]
Thanks, I see now how to add the Repository. 
I have never upgraded the Kernel, it came with Fedora 28. Do you know of any good resources I can follow to accomplish that? I think I will give it a go after work today.

**Comment by ktdreyer** [comment]
Sure, to install the very latest kernel from Fedora's "updates-testing" repository on to your computer, run this command:
```
sudo dnf -y update --enablerepo=\*-testing
```
(... and if there is a newer Fedora kernel available, DNF will install it.)

Then reboot your computer, `uname -r` will show the new kernel version.

**Comment by dcabrejas** [comment]
Works great, thank you!
