### ISSUE TITLE
Question about wl-kmod

### ISSUE THREAD

**Issue by izaera** [ktdreyer/facetimehd-kmod-rpm#3]
Hi there:

My question is regarding the `wl-kmod` module you are packaging next to `facetimehd`. 

What's it for? 

I guess it is a driver for the wifi card of MacBook Pros, but what are the differences between using that and the built-in `brcmfmac` driver? :thinking: 

Thanks :-)

**Comment by izaera** [comment]
OK, I found out that it is the proprietary driver -> https://wiki.debian.org/wl

**Comment by ktdreyer** [comment]
Hi Ivan, that's right, it's for the proprietary wifi driver.

I don't have my MacBook Pro any more so I've abandoned this project. I should update the README to make that clear.

**Comment by ktdreyer** [comment]
I've updated the README in https://github.com/ktdreyer/facetimehd-kmod-rpm/commit/1a8a75f6f901f475b1917b42eb64f09b46c47ca1
